config/routes.rb
Rails.application.routes.draw do
  get 'notes/index'
  get 'notes/new'
  get 'notes/create'
  get 'notes/edit'
  get 'notes/update'
  get 'notes/destroy'
  get 'users/show'
  authenticated :user do
    root to: "subjects#index"
  end

  resources :subjects do
    resources :class_memberships, only: [:create]
    resources :users, only: [:show] do
      resources :appointments, only: [:create]
    end
  end

  resources :users, only: [] do
    resources :notes, only: [:create]
  end
  resources :notes, only: [:index, :destroy]

  resources :daily_emotions, only: [:new]

  resources :appointments, only: [:show, :index, :destroy, :edit, :update]

  resources :home, only: [:index]

  resources :users do
    resources :appointments, only: [:create]
  end
  resources :class_memberships, only: [:destroy]
  resources :daily_emotions, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index', as: "landing"
  devise_for :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
    belongs_to :student, foreign_key: 'student_id', class_name: 'User'
    belongs_to :teacher, foreign_key: 'teacher_id', class_name: 'User'
  end
  

app/models/class_membership.rb
class ClassMembership < ApplicationRecord
    belongs_to :user
    belongs_to :subject
    validates :user, presence: true
    validates :subject, presence: true
  end
  

app/models/daily_emotion.rb
class DailyEmotion < ApplicationRecord
    belongs_to :emotion
    belongs_to :user
  end
  

app/models/emotion.rb
class Emotion < ApplicationRecord
    has_many :daily_emotions
    validates :rating, presence: true
    enum rating: { "😞" => 1,
                   "😕" => 2,
                   "😐" => 3,
                   "🙂" => 4,
                   "😁" => 5 }
    def name
      rating
    end
  
    def number
      rating_hash = { "😞" => 1,
                   "😕" => 2,
                   "😐" => 3,
                   "🙂" => 4,
                   "😁" => 5 }
      rating_hash[self.rating]
    end
  
    def color
      num = self.number
      case num
      when 1 then '#F25855'
      when 2 then '#F7955F'
      when 3 then '#F7B363'
      when 4 then '#F7D167'
      when 5 then '#ABD682'
      end
    end
  end
  
      # when 1 then '#A33141'
      # when 2 then '#F08853'
      # when 3 then '#EEDD9D'
      # when 4 then '#6B92AB'
      # when 5 then '#D0FBDF'
  

app/models/note.rb
class Note < ApplicationRecord
    belongs_to :student, foreign_key: 'student_id', class_name: 'User'
    belongs_to :teacher, foreign_key: 'teacher_id', class_name: 'User'
  end
  

app/models/subject.rb
class Subject < ApplicationRecord
    belongs_to :user
    has_many :class_memberships
    has_many :class_members, through: :class_memberships, source: :user, class_name: 'User'
    validates :name, presence: true
    validates :user, presence: true
  end
  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :teacher_appointment_relationships, foreign_key: :teacher_id, class_name: 'Appointment'
         has_many :teacher_appointments, through: :teacher_appointment_relationships, source: :teacher
         has_many :student_appointment_relationships, foreign_key: :student_id, class_name: 'Appointment'
         has_many :student_appointments, through: :student_appointment_relationships, source: :student
         has_many :daily_emotions
         has_many :emotions, through: :daily_emotions
       
         has_many :teacher_note_relationships, foreign_key: :teacher_id, class_name: 'Note'
         has_many :teacher_notes, through: :teacher_note_relationships, source: :teacher
         has_many :student_note_relationships, foreign_key: :student_id, class_name: 'Note'
         has_many :student_notes, through: :student_note_relationships, source: :student
       
         has_many :subjects
         has_many :class_leaderships, through: :subjects, source: :class_membership
         has_many :students, through: :class_leaderships, source: :user
         has_many :class_memberships
         has_many :student_subjects, through: :class_memberships, source: :subject
         has_many :teachers, through: :student_subjects, source: :user
       
         validates :first_name, presence: true
         validates :last_name, presence: true
       
         has_many :teacher_note_relationships, foreign_key: :teacher_id, class_name: 'Note'
         has_many :student_note_relationships, foreign_key: :student_id, class_name: 'Note'
       
         scope :teachers, -> { where(role: 'teacher') }
         scope :students, -> { where(role: 'student') }
       
         # used to check if child has already submitted an emotion
         def has_submitted_today?
           daily_emotions.where(date: DateTime.today).any?
         end
       
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def create
    @note = Note.new(note_params)
    @note.teacher = current_user
    @subject = Subject.find(params[:subject_id])
    @student = User.find(params[:user_id])
    @note.student = User.find(params[:user_id])
    authorize @note
    if @note.save
      respond_to do |format|
        format.html { redirect_to subject_user_path(Subject.find(params[:subject_id]), @note.student) }
        format.js
      end
    else
      respond_to do |format|
        format.html { render 'users/show' }
        format.js
      end
    end
  end

  def destroy
    @note = Note.find(params[:id])
    @note.destroy
    redirect_to subject_user_path(Subject.find(params[:subject_id]), @note.student)
  end

  private

  def note_params
    params.require(:note).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @subject = Subject.find(params[:subject_id])
    @appointment = Appointment.new
    @user = current_user
    @student = User.find(params[:id])
    @note = Note.new
    @daily_emotions = @student.daily_emotions
    @dailynumber = @daily_emotions.map { |emo| [emo.created_at, emo.emotion.number] }
    authorize current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/daily_emotions_helper.rb
module DailyEmotionsHelper
end

app/helpers/emotions_helper.rb
module EmotionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
    def meta_title
      content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
    end
  
    def meta_description
      content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
    end
  
    def meta_image
      meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
      # little twist to make it work equally with an asset or a url
      meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
    end
  end
  

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Sammi- Supporting teachers, supporting students</title>
    <%= favicon_link_tag %>

    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>

    <% if params[:action] != 'new' || params[:controller] == 'pages' && params[:action] == 'home' %>
      <%= render 'shared/navbar' %>
    <% end %>
    <%= render 'shared/flashes' %>
    <% if params[:controller] == 'subjects' && params[:action] == 'show' || params[:controller] == 'devise/sessions' && params[:action] == 'new' ||  params[:controller] == 'home' %>
      <%= yield %>
    <% else %>
      <div class="container">
        <%= yield %>
      </div>
    <% end %>

    <% if params[:controller] == 'home' %>
      <%= render 'shared/footer' %>
    <% end %>
  </body>
</html>

app/views/shared/_appointments_form.html.erb
<div class="container">
  <div class="row justify-center-center">
    <div class="col-12">
      <%= form_with(model: [@subject, @student, @appointment]) do |f| %>
        <%= f.text_field :comment %>
        <%= f.text_field :date, as: :string, required: false, input_html: {class: "datepicker"} %>
        <%= f.submit 'Submit',class: "btn btn-sammi"%>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright d-none d-sm-block">
    Here to support <i class="fas fa-heart"></i> - Sammi Team
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to subjects_path, class: "navbar-brand" do %>
    <h1 id="sammi-logo">Sammi</h1>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item-s">
          <%= link_to "Subjects", subjects_path, class: "nav-link" %>
        </li>
        <li class="nav-item-s">
          <%= link_to "Appointments", appointments_path , class: "nav-link" %>
        <li class="nav-item dropdown">
          <%= image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "About", landing_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_new_class.html.erb
<div class="container">
  <div class="row justify-center-center">
    <div class="col-12">
      <%= form_with(model: @subject) do |f| %>
        <%= f.text_field :name %>
        <%= f.text_field :room %>
        <%= f.text_field :photo %>
        <%= f.submit 'Submit', class: "btn btn-sammi"%>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_new_student.html.erb
<div class="container">
  <div class="row justify-center-center">
    <div class="col-12">
      <p>Your Link: askjdna&ajd18ha</p>
    </div>
  </div>
</div>

app/views/shared/_note_form.html.erb
 <%= form_with(model: [student, note], remote: true) do |f| %>
    <%= hidden_field_tag :subject_id, subject.id %>
    <div class="d-flex align-items-center justify-content-between">
      <%= f.text_field :content, as: :string, input_html: { class: 'form-control m-0' }, wrapper_html: { class: 'm-0' }, placeholder: 'Type here...', label: false, disabled: true %>
      <%= f.submit 'Submit', disabled: true, class:'btn btn-sammi notes-button'%>
    </div>
  <% end %>

app/views/shared/_notes.html.erb
<div class="chat-note">
  <div class="note-teacher">
    <%= image_tag note.teacher.photo, class: "avatar" %>
  </div>
  <div class="chatz">
    <p class="chat-note-message"><%= note.content %></p>
    <div class="chat-note-time"><%= note.created_at.strftime("%A, %d %b %Y %l:%M %p") %> | <%= note.teacher.subjects.first&.name %></div>
  </div>
</div>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>

    <nav>
      <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
      <%= link_to t('simple_calendar.today', default: 'Today'), calendar.url_for_today_view %>
      <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
    </nav>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% instance_exec(day, calendar.sorted_events_for(day), &passed_block) %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <time datetime="<%= start_date.strftime('%Y-%m') %>" class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></time>

    <nav>
      <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
      <%= link_to t('simple_calendar.today', default: 'Today'), calendar.url_for_today_view %>
      <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
    </nav>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% instance_exec(day, calendar.sorted_events_for(day), &passed_block) %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <span class="calendar-title">
      <%= t('simple_calendar.week', default: 'Week') %>
      <%= calendar.week_number %>
      <% if calendar.number_of_weeks > 1 %>
        - <%= calendar.end_week %>
      <% end %>
    </span>

    <nav>
      <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
      <%= link_to t('simple_calendar.today', default: 'Today'), calendar.url_for_today_view %>
      <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
    </nav>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% instance_exec(day, calendar.sorted_events_for(day), &passed_block) %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>