config/routes.rb
Rails.application.routes.draw do
  get 'notes/index'
  get 'notes/new'
  get 'notes/create'
  get 'notes/edit'
  get 'notes/update'
  get 'notes/destroy'
  get 'users/show'
  authenticated :user do
    root to: "subjects#index"
  end

  resources :subjects do
    resources :class_memberships, only: [:create]
    resources :users, only: [:show] do
      resources :appointments, only: [:create]
    end
  end

  resources :users, only: [] do
    resources :notes, only: [:create]
  end
  resources :notes, only: [:index, :destroy]

  resources :daily_emotions, only: [:new]

  resources :appointments, only: [:show, :index, :destroy, :edit, :update]

  resources :home, only: [:index]

  resources :users do
    resources :appointments, only: [:create]
  end
  resources :class_memberships, only: [:destroy]
  resources :daily_emotions, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index', as: "landing"
  devise_for :user
end

app/models/subject.rb
class Subject < ApplicationRecord
    belongs_to :user
    has_many :class_memberships
    has_many :class_members, through: :class_memberships, source: :user, class_name: 'User'
    validates :name, presence: true
    validates :user, presence: true
  end
  

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def index
    @subjects = policy_scope(Subject)
    @subject = Subject.new
    @emotions_hash = {}
    @subjects.each do |subject|
      @emotions_hash[subject.id] = subject.class_members.map { |stu| stu.daily_emotions.first.emotion.number }
    end
    # emotions_map = Subject.first.class_members.map { |stu| stu.daily_emotions.first.emotion.number }
    @emotions_hash = @emotions_hash.map do |k, v|
      [k, v.group_by{|r| r}]
    end

    @emotions_hash = @emotions_hash.to_h

    @emotions_hash = @emotions_hash.map do |k, v|
      [k, v.map { |k, v| [k, v.length] }.to_h]
    end

    @emotions_hash.map! do |subject|
      [subject[0], subject[1].map{ |k, v| [k, v.to_f / subject[1].values.inject(:+)] }.to_h]
    end

    @hsh = {}
    @emo_array = @emotions_hash.map{|subject|subject[1]}.map{|h|h.map{|k, v|k*v}.sum}

    counter = 0
    @subjects.each do |subject|
      @hsh[subject.id] = @emo_array[counter]
      counter +=1
      # @emo_array.each do |emo|
      #   @hsh[subject.id] = emo
      # end

    end

    @avergae_hash = {}


    # grouped_emotions = emotions_map.group_by{|r| r}
    # length = emotions_map.length
    # count_emos = grouped_emotions.map { |key, value| { key => value.length } }
    # @emo_index = count_emos.map { |i| i.map { |key, value| { key => (value / length.to_f) * 100 } } }.map { |i| i.first }.reduce Hash.new, :merge
    # @emo_average = @emo_index.map {|k, v| k * v }.sum / 100
    # raise

    @random_proportions =
      { 2 => [25, 20, 35, 10, 10],
        5 => [10, 10, 10, 5, 65],
        3 => [8, 52, 15, 5, 20],
        4 => [10, 10, 10, 20, 50],
        4.5 => [13, 27, 20, 30, 30] }
  end

  def show
    @subject = Subject.find(params[:id])
    emotion_map = @subject.class_members.map {|student| student.daily_emotions.first.emotion.number }
    grouped_emotions = emotion_map.group_by{|r| r}
    length = emotion_map.length
    count_emos = grouped_emotions.map { |key, value| { key => value.length } }
    @emo_prop = count_emos.map { |i| i.map { |key, value| { key => (value / length.to_f) * 100 } } }.map { |i| i.first }.reduce Hash.new, :merge
    @emo_average = @emo_prop.map { |k, v| k * v }.sum / 100
    authorize @subject
  end

  def new
    @user = current_user
  end

  def create
    @subject = Subject.new(subject_params)
    @subject.user = current_user
    authorize @subject
    if @subject.save
      redirect_to subjects_path
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy
    authorize @subject
    redirect_to subjects_path
  end

  def subject_params
    params.require(:subject).permit(:name, :room, :photo)
  end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/index.html.erb
<div class='d-flex justify-content-between my-4 '>
  <h1>Your Classes</h1>

  <button class="btn btn-sammi" type="button" data-toggle="modal" data-target="#exampleModal">
    Add new class
  </button>

  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content" style='border-radius:10px'>
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">New Class</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= render 'shared/new_class' %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class='row'>

    <% @emotions_hash.each do |subject| %>
      <div class='col-12 col-lg-6'>
        <%= link_to subject_path(subject[0]) do %>

          <div class="card-subjects">
            <img src='<%= asset_path(Subject.find(subject[0]).photo) %>'/>
            <div class="card-subjects-infos">
              <h2><%= Subject.find(subject[0]).name %></h2>

              <% if Subject.find(subject[0]).class_members.length > 0 %>
                <div class='d-flex justify-content-between'>
                    <p><%= Subject.find(subject[0]).class_members.length %> students</p>
                    <p id='emotion'><%= Emotion.find(@hsh[subject[0]]).rating %>

                </div>
                <br>
                <div class="progress">
                  <div class="progress-bar" role="progressbar" style="background-color: <%= Emotion.first.color %>;width: <%= subject[1][1] ? subject[1][1] * 100 : 0 %>%" aria-valuenow="<%= subject[1][1] ? subject[1][1] * 100 : 0 %>" aria-valuemin="0" aria-valuemax="100" data-toggle='tooltip' data-placement="top" title="<%= Emotion.first.rating %>"></div>
                  <div class="progress-bar" role="progressbar" style="background-color: <%= Emotion.second.color %>; width: <%= subject[1][2] ? subject[1][2] * 100 : 0 %>%" aria-valuenow="<%= subject[1][2] ? subject[1][2] * 100 : 0 %>" aria-valuemin="0" aria-valuemax="100" data-toggle='tooltip' data-placement="top" title="<%= Emotion.second.rating %>"></div>
                  <div class="progress-bar" role="progressbar" style="background-color: <%= Emotion.third.color %>; width: <%= subject[1][3] ? subject[1][3] * 100 : 0 %>%" aria-valuenow="<%= subject[1][3] ? subject[1][3] * 100 : 0 %>" aria-valuemin="0" aria-valuemax="100" data-toggle='tooltip' data-placement="top" title="<%= Emotion.third.rating %>"></div>
                  <div class="progress-bar" role="progressbar" style="background-color: <%= Emotion.fourth.color %>; width: <%= subject[1][4] ? subject[1][4] * 100 : 0 %>%" aria-valuenow="<%= subject[1][4] ? subject[1][4] * 100 : 0 %>" aria-valuemin="0" aria-valuemax="100" data-toggle='tooltip' data-placement="top" title="<%= Emotion.fourth.rating %>"></div>
                  <div class="progress-bar" role="progressbar" style="background-color: <%= Emotion.fifth.color %>; width: <%= subject[1][5] ? subject[1][5] * 100 : 0 %>%" aria-valuenow="<%= subject[1][5] ? subject[1][5] * 100 : 0 %>" aria-valuemin="0" aria-valuemax="100" data-toggle='tooltip' data-placement="top" title="<%= Emotion.fifth.rating %>"></div>
                </div>

              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>

</div>

app/views/subjects/show.html.erb
<div class='subject-banner' style="background-image: linear-gradient(rgba(0, 0, 0, 0.1), rgba(0, 0, 0, 0.1)), url('<%= asset_path(@subject.photo) %>');">

  <div class="container d-flex banner-text m-auto">
    <div class='col-6 mt-2'>
      <h1><%= @subject.name %></h1>
      <p><%= @subject.class_members.length %> students registered in this class</p>
    </div>
    <div class='col-6 d-flex' style='justify-content: flex-end;'>
      <!-- Button trigger modal -->
      <button type="button" class="btn btn-sammi">Add Student</button>
    </div>
  </div>

</div>
<div class='container p-0'>
<% if @subject.class_members.length > 0 %>
<!-- This will be a bar showing the proportion for the entire class once we agree on a color scheme -->
<div class='class-progress'>
  <div class="progress">
    <div class="progress-bar" role="progressbar" style="background-color: <%= Emotion.first.color %>;width: <%= @emo_prop[Emotion.first.number] %>%" aria-valuenow="<%= @emo_prop[Emotion.first.number] %>" aria-valuemin="0" aria-valuemax="100" data-toggle='tooltip' data-placement="top" title="<%= Emotion.first.rating %>"></div>
    <div class="progress-bar" role="progressbar" style="background-color: <%= Emotion.second.color %>; width: <%= @emo_prop[Emotion.second.number] %>%" aria-valuenow="<%= @emo_prop[Emotion.second.number] %>" aria-valuemin="0" aria-valuemax="100" data-toggle='tooltip' data-placement="top" title="<%= Emotion.second.rating %>"></div>
    <div class="progress-bar" role="progressbar" style="background-color: <%= Emotion.third.color %>; width: <%= @emo_prop[Emotion.third.number] %>%" aria-valuenow="<%= @emo_prop[Emotion.third.number] %>" aria-valuemin="0" aria-valuemax="100" data-toggle='tooltip' data-placement="top" title="<%= Emotion.third.rating %>"></div>
    <div class="progress-bar" role="progressbar" style="background-color: <%= Emotion.fourth.color %>; width: <%= @emo_prop[Emotion.fourth.number] %>%" aria-valuenow="<%= @emo_prop[Emotion.fourth.number] %>" aria-valuemin="0" aria-valuemax="100" data-toggle='tooltip' data-placement="top" title="<%= Emotion.fourth.rating %>"></div>
    <div class="progress-bar" role="progressbar" style="background-color: <%= Emotion.fifth.color %>; width: <%= @emo_prop[Emotion.fifth.number] %>%" aria-valuenow="<%= @emo_prop[Emotion.fifth.number] %>" aria-valuemin="0" aria-valuemax="100" data-toggle='tooltip' data-placement="top" title="<%= Emotion.fifth.rating %>"></div>
  </div>
</div>
<div class="student-index">
  <div class='row'>
    <div class='col-12 col-md-9'>
      <div class='row'>
        <% @subject.class_members.each do |member| %>
          <div class='col-12 col-md-12 col-lg-6'>
          <%= link_to subject_user_path(@subject, member) do %>
            <div class='card-container mb-4' <%#= member.daily_emotions.first.emotion.color %>>
              <div class='row'>
                <div class='col-4 pr-0'>
                  <div class="card-product">
                    <%= image_tag asset_path(member.photo), class: "avatar-large m-auto", alt: "avatar-large" %>
                  </div>
                </div>
                <div class='col-4 justify-content-center'>
                  <h2 style='padding-top:25%; font-size:16px'><%= member.first_name %> <%= member.last_name %></h2>
                  <p style='font-size:11px'>Last Updated Today at 08:1<%= rand(1..9) %></p>
                </div>
                <div class='col-4 pl-0'>
                  <div class="card-product d-flex">
                    <p id="emotion"><%= member.daily_emotions.first.emotion.rating %></p>
                    <% if member.daily_emotions.first.emotion.number > member.daily_emotions.second.emotion.number %>
                      <i class="fas fa-arrow-up"></i>
                      <% elsif member.daily_emotions.first.emotion.number < member.daily_emotions.second.emotion.number %>
                      <i class="fas fa-arrow-down"></i>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
    <div class='col-3'>
      <div class='stats-container'>
        <div class='stats-sticky d-none d-md-block'>
          <div class='row d-flex mb-0' style='justify-content:center;padding:10px;'>
            <h2>Mood Overview</h2>
          </div>
          <br>
          <div class='row d-flex'style='align-items:center'>
          <% Emotion.all.each do|emo| %>
            <div class='col-6 mb-2'>
              <h2 style='margin-bottom: 0;text-align: center;'><%= emo.rating %></h2>
            </div>
            <div class='col-6 p-0 mb-2'>
              <div class="bar" style="width:<%= @emo_prop[emo.number] %>%; height: 15px; background-color: <%= emo.color %>;"></div>
            </div>
          <% end %>
          </div>
          <br>
          <div class='row d-flex mb-0' style='justify-content:center;'>
            <h2>Average</h2>
          </div>
          <div class='row d-flex mb-0' style='justify-content:center;'>
            <p id='emotion'><%= Emotion.find(@emo_average.round).rating%></p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>